-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles (Extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  xp integer default 0,
  level integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Categories
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text, -- Material Symbol name
  slug text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Recipes
create table public.recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  time_minutes integer,
  difficulty text check (difficulty in ('Fácil', 'Intermediário', 'Difícil')),
  calories integer,
  rating numeric default 0,
  slug text unique,
  author_id uuid references public.profiles(id),
  is_featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Recipe Categories (Many-to-Many)
create table public.recipe_categories (
  recipe_id bigint references public.recipes(id) on delete cascade,
  category_id bigint references public.categories(id) on delete cascade,
  primary key (recipe_id, category_id)
);

-- 5. Ingredients
create table public.ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint references public.recipes(id) on delete cascade,
  name text not null,
  amount text,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Steps (Gamification Core)
create table public.steps (
  id bigint generated by default as identity primary key,
  recipe_id bigint references public.recipes(id) on delete cascade,
  order_index integer not null,
  title text not null,
  description text,
  image_url text,
  timer_seconds integer,
  xp_reward integer default 10,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Favorites
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  recipe_id bigint references public.recipes(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, recipe_id)
);

-- 8. Completed Recipes
create table public.completed_recipes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  recipe_id bigint references public.recipes(id) on delete cascade not null,
  xp_earned integer default 0,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 9. Influencers
create table public.influencers (
  id bigint generated by default as identity primary key,
  name text not null,
  avatar_url text,
  social_link text,
  is_of_the_week boolean default false,
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 10. Influencer Recipes (Relation table)
create table public.influencer_recipes (
  id bigint generated by default as identity primary key,
  influencer_id bigint references public.influencers(id) on delete cascade not null,
  recipe_id bigint references public.recipes(id) on delete cascade not null,
  tag text default 'APROVADO', -- ex: APROVADO, DICA, LEVE
  subtitle text, -- ex: Consumo Diário, Pós Treino
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(influencer_id, recipe_id)
);

-- RLS Policies (Row Level Security)
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_categories enable row level security;
alter table public.ingredients enable row level security;
alter table public.steps enable row level security;
alter table public.favorites enable row level security;
alter table public.completed_recipes enable row level security;
alter table public.influencers enable row level security;
alter table public.influencer_recipes enable row level security;

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (
    new.id,
    split_part(new.email, '@', 1),
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$;

-- Trigger to call function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Profiles Policies
create policy "Profiles are viewable by authenticated users." on public.profiles for select to authenticated using (true);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);

-- Public Read Policies (Content)
create policy "Categories are viewable by everyone." on public.categories for select using (true);
create policy "Recipes are viewable by everyone." on public.recipes for select using (true);
create policy "Recipe Categories are viewable by everyone." on public.recipe_categories for select using (true);
create policy "Ingredients are viewable by everyone." on public.ingredients for select using (true);
create policy "Steps are viewable by everyone." on public.steps for select using (true);
create policy "Influencers are viewable by everyone." on public.influencers for select using (true);
create policy "Influencer Recipes are viewable by everyone." on public.influencer_recipes for select using (true);

-- User Data Policies (Private)
create policy "Users can view their own favorites" on public.favorites for select using (auth.uid() = user_id);
create policy "Users can add their own favorites" on public.favorites for insert with check (auth.uid() = user_id);
create policy "Users can delete their own favorites" on public.favorites for delete using (auth.uid() = user_id);

create policy "Users can view their own completed recipes" on public.completed_recipes for select using (auth.uid() = user_id);
create policy "Users can add their own completed recipes" on public.completed_recipes for insert with check (auth.uid() = user_id);
create policy "Users can update their own completed recipes" on public.completed_recipes for update using (auth.uid() = user_id);

-- Insert Mock Data (Categories)
insert into public.categories (name, icon, slug) values
('Populares', 'trending_up', 'populares'),
('Italiana', 'local_pizza', 'italiana'),
('Fitness', 'fitness_center', 'fitness'),
('Sobremesas', 'cake', 'sobremesas'),
('Vegetariana', 'eco', 'vegetariana');

-- Insert Influencer of the week
insert into public.influencers (name, avatar_url, social_link, is_of_the_week, bio)
values ('Virginia Fonseca', 'https://lh3.googleusercontent.com/aida-public/AB6AXuBCwaOEvJhqMAVghjm5wcjQ_nwtLEDvzVsWdAyohCcTJmMtpN1mrfOX7Dd7-tVaDJDMNgr85MXfld5lMgUqmK1suGOnB8wF5n0yT-4bH-1njXTdKLIVWjz1Z4kGLk-yX4DoIg3tW_cxbBVcgzV7Yj9jl4YAr0O1752WIIDjWGrco5in9SJCt1FVt94tuhhrSQbI-pPQH6qzcpdFrcluWQrL72Ky6ugPTnJpYTJu0lLxmdE6tr23EsIWs7d5r9_LJxZiQ4uOfnyUPBAR', 'https://instagram.com/virginia', true, 'Pratos que eu consumo no meu dia a dia');
