-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Profiles (Extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  xp integer default 0,
  level integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Categories
create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text, -- Material Symbol name
  slug text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Recipes
create table public.recipes (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  time_minutes integer,
  difficulty text check (difficulty in ('Fácil', 'Intermediário', 'Difícil')),
  calories integer,
  rating numeric default 0,
  slug text unique,
  author_id uuid references public.profiles(id),
  is_featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Recipe Categories (Many-to-Many)
create table public.recipe_categories (
  recipe_id bigint references public.recipes(id) on delete cascade,
  category_id bigint references public.categories(id) on delete cascade,
  primary key (recipe_id, category_id)
);

-- 5. Ingredients
create table public.ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint references public.recipes(id) on delete cascade,
  name text not null,
  amount text,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Steps (Gamification Core)
create table public.steps (
  id bigint generated by default as identity primary key,
  recipe_id bigint references public.recipes(id) on delete cascade,
  order_index integer not null,
  title text not null,
  description text,
  image_url text,
  timer_seconds integer,
  xp_reward integer default 10,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Row Level Security)
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_categories enable row level security;
alter table public.ingredients enable row level security;
alter table public.steps enable row level security;

-- Public Read Policies
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Categories are viewable by everyone." on public.categories for select using (true);
create policy "Recipes are viewable by everyone." on public.recipes for select using (true);
create policy "Recipe Categories are viewable by everyone." on public.recipe_categories for select using (true);
create policy "Ingredients are viewable by everyone." on public.ingredients for select using (true);
create policy "Steps are viewable by everyone." on public.steps for select using (true);

-- Insert Mock Data (Categories)
insert into public.categories (name, icon, slug) values
('Populares', 'trending_up', 'populares'),
('Italiana', 'local_pizza', 'italiana'),
('Fitness', 'fitness_center', 'fitness'),
('Sobremesas', 'cake', 'sobremesas'),
('Vegetariana', 'eco', 'vegetariana');
